# Site settings
title: Top Quark In Town Comics
email: opabinia@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Strange and charming comics by Mehitabel Glenhaber
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://topquarkintown.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty
